apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: myrc
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: v1
    kind: ReplicationController
    name: myrc
  targetCPUUtilizationPercentage: 80
status:
  currentReplicas: 0
  desiredReplicas: 0
