apiVersion: v1
kind: Pod
metadata:
   name: mypod
   labels:
      app: myapp
      env: dev
spec:
   containers:
   - name: nginx
     image: nginx:latest
     ports:
     - containerPort: 80
     resources:
       limits:
          cpu: "1000m"
          memory: "512M"
       requests:
          cpu: "500m"
          memory: "128M"
   affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
             - key: disk
               operator: In
               values:
               - ssd
   tolerations: 
   - key: cpu
     operator: Equal
     value: "intel"
     effect: "NoExecute"

#   nodeName: node2
#   nodeSelector:
#     disk: ssd

