apiVersion: v1
kind: Pod
metadata:
   name: pod-aff-req
   labels:
      app: pod-req-aff
spec:
   containers:
   - name: nginx
     image: nginx:latest
     ports:
     - containerPort: 80
     resources:
       limits:
          cpu: "1000m"
          memory: "512M"
       requests:
          cpu: "500m"
          memory: "128M"
   affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
             matchExpressions:
             - key: app
               operator: In
               values:
               - myapp
          topologyKey: "kubernetes.io/hostname"
#   tolerations: 
#   - key: cpu
#     operator: Equal
#     value: "intel"
#     effect: "NoExecute"

#   nodeName: node2
#   nodeSelector:
#     disk: ssd

