apiVersion: v1
kind: Pod
metadata:
   name: mpod
   annotations:
        description: this is sample pod
   labels:
      app: myapp
spec:
   containers:
   - name: nginx
     image: nginx:latest
#     imagePullPolicy: Always
     ports:
     - containerPort: 80
     resources:
       limits:
          cpu: "1000m"
          memory: "512M"
       requests:
          cpu: "500m"
          memory: "128M"
     livenessProbe:
       tcpSocket:
         port: 80
       initialDelaySeconds: 10
       periodSeconds: 5

   - name: con2
     image: tomcat:latest
     ports:
     - containerPort: 8080
     resources:
       limits:
          cpu: "500m"
          memory: "512M"
       requests:
          cpu: "250m"
          memory: "128M"
     
#   nodeName: node2
#   nodeSelector:
#     disk: ssd

---
apiVersion: v1
kind: Service
metadata:
   name: mypod-svc
spec:
   type: NodePort
   selector:
      app: myapp
   ports:
   - port: 80
     nodePort: 30123


